import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "Georgia", "serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      colors: {
        background: "var(--bg)",
        foreground: "var(--ink)",
        app: {
          bg: "var(--bg)",
          "bg-2": "var(--bg-2)",
          canvas: "var(--canvas)",
          card: "var(--card)",
          surface: "var(--surface)",
          "surface-2": "var(--surface-2)",
          hover: "var(--hover)",
          ink: "var(--ink)",
          ink2: "var(--ink-2)",
          text: "var(--ink-3)",
          muted: "var(--muted)",
          border: "var(--border)",
          "border-strong": "var(--border-2)",
          brand: "var(--accent)",
          "brand-dark": "color-mix(in oklab, var(--accent) 82%, black)",
          "brand-soft": "var(--accent-soft)",
          "brand-mid": "var(--accent-soft)",
          danger: "var(--danger)",
          ok: "var(--positive)",
          warning: "var(--warning)",
          link: "var(--link)",
          sidebar: {
            bg: "var(--sidebar-bg)",
            ink: "var(--sidebar-ink)",
            muted: "var(--sidebar-muted)",
            active: "var(--sidebar-active-bg)",
            "active-ink": "var(--sidebar-active-ink)",
          },
          "st-todo": "var(--surface-2)",
          "st-todo-ink": "var(--ink-3)",
          "st-planned": "var(--accent-soft)",
          "st-planned-ink": "var(--accent-ink)",
          "st-progress": "color-mix(in oklab, var(--warning) 22%, var(--surface-2))",
          "st-progress-ink": "var(--warning)",
          "st-done": "color-mix(in oklab, var(--positive) 18%, var(--surface-2))",
          "st-done-ink": "var(--positive)",
          "st-blocked": "color-mix(in oklab, var(--danger) 16%, var(--surface-2))",
          "st-blocked-ink": "var(--danger)",
          "st-default": "var(--surface-2)",
          "st-default-ink": "var(--ink-3)",
          row: "var(--surface-2)",
        },
      },
      boxShadow: {
        card: "var(--shadow-1)",
        "card-lg": "var(--shadow-2)",
        pop: "var(--shadow-pop)",
      },
      borderRadius: {
        hs: "var(--radius)",
        "hs-sm": "var(--radius-sm)",
        "hs-lg": "var(--radius-lg)",
      },
    },
  },
  plugins: [],
} satisfies Config;
